version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Logging in testing ...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - aws s3 cp Dockerfile s3://wipo-test-vishal-s3/